### ISSUE TITLE
Mouse hover steals focus

### ISSUE THREAD

**Issue by R-Smith** [gcla/gowid#17]
I have a pretty simple layout with a few columns and piles - For whatever reason, if you hover the mouse over certain parts of the layout, it will steal the focus.  I'm pasting in a simple example.  Notice that hovering your mouse over the text on the right side, causes the button below it to suddenly get focus.

```golang
package main

import (
	"github.com/gcla/gowid"
	"github.com/gcla/gowid/widgets/button"
	"github.com/gcla/gowid/widgets/columns"
	"github.com/gcla/gowid/widgets/edit"
	"github.com/gcla/gowid/widgets/framed"
	"github.com/gcla/gowid/widgets/pile"
	"github.com/gcla/gowid/widgets/styled"
	"github.com/gcla/gowid/widgets/text"
)

func main() {
	palette := gowid.Palette{
		"frameActive":   gowid.MakePaletteEntry(gowid.ColorYellow, gowid.ColorBlack),
		"frameInactive": gowid.MakePaletteEntry(gowid.ColorDarkGray, gowid.ColorBlack),
		"editActive":    gowid.MakePaletteEntry(gowid.ColorWhite, gowid.ColorDarkBlue),
		"editInactive":  gowid.MakePaletteEntry(gowid.ColorDarkGray, gowid.ColorBlack),
		"btnActive":     gowid.MakePaletteEntry(gowid.ColorRed, gowid.ColorBlack),
		"btnInactive":   gowid.MakePaletteEntry(gowid.ColorDarkGray, gowid.ColorBlack),
	}
	// Left side: styled edit widget in a styled frame.
	leftEdit := styled.NewExt(
		edit.New(edit.Options{Text: "This is an edit widget"}),
		gowid.MakePaletteRef("editInactive"),
		gowid.MakePaletteRef("editActive"))
	leftFrame := styled.NewExt(
		framed.NewUnicode(leftEdit),
		gowid.MakePaletteRef("frameInactive"),
		gowid.MakePaletteRef("frameActive"))

	// Right side:
	// Text widgets in columns.
	rightCols := columns.New([]gowid.IContainerWidget{
		&gowid.ContainerWidget{IWidget: text.New("Text in column A"), D: gowid.RenderWithUnits{U: 20}},
		&gowid.ContainerWidget{IWidget: text.New("Text in column B"), D: gowid.RenderWithUnits{U: 20}},
	})

	// Styled button.
	rightBtn := styled.NewExt(
		button.New(text.New("  Button  ")),
		gowid.MakePaletteRef("btnInactive"),
		gowid.MakePaletteRef("btnActive"))

	rightRows := pile.New([]gowid.IContainerWidget{
		&gowid.ContainerWidget{IWidget: rightCols, D: gowid.RenderWithUnits{U: 2}},
		&gowid.ContainerWidget{IWidget: rightBtn, D: gowid.RenderFixed{}},
	})
	rightFrame := styled.NewExt(
		framed.NewUnicode(rightRows),
		gowid.MakePaletteRef("frameInactive"),
		gowid.MakePaletteRef("frameActive"))

	// Combine left and right frames.
	cols := columns.New([]gowid.IContainerWidget{
		&gowid.ContainerWidget{IWidget: leftFrame, D: gowid.RenderWithUnits{U: 30}},
		&gowid.ContainerWidget{IWidget: rightFrame, D: gowid.RenderWithWeight{W: 1}},
	})

	app, _ := gowid.NewApp(gowid.AppArgs{View: cols, Palette: palette})
	app.SimpleMainLoop()
}
```

**Comment by R-Smith** [comment]
It seems to only happen with a columns widget.  Pile widgets don't have this behavior.  In a way, mouse hovering causing focus events is a nice feature, just inconsistent with the library.  A separate mouse focus widget might be kind of cool.

I came up with a fix for the columns widget, but I don't know if it's the right way to approach it.  What do you think of this?

On widgets/columns/columns.go line 300:
**Original**
```golang
if evm, ok := ev.(*tcell.EventMouse); ok {
```

**My proposal**
```golang
if evm, ok := ev.(*tcell.EventMouse); ok && evm.Buttons() != 0 {
```

**Comment by R-Smith** [comment]
Hang on, that proposed fix causes other issues with mouse clicks in columns.  I'll see if I can work out a better solution.

**Comment by gcla** [comment]
Thanks :) I'll take a look at your examples this weekend

**Comment by gcla** [comment]
Hi @R-Smith - could you try your example again with gowid updated to commit 30a07938beee662e1d82101a10f5ba8dadddb9f5? Let me know!

**Comment by gcla** [comment]
Err, I changed my mind :confused: Could you try the branch `mousefocus` instead? I'm not 100% sure of these changes yet, though so far they seem well-behaved. I put them on a branch for a couple of days out of caution. You can make your app use this branch with something like this, assuming your example above is called `myapp.go`:

```bash
mkdir myapp
mv myapp.go myapp/
cd myapp
go mod init myapp
export GO111MODULE=on
go get github.com/gcla/gowid@mousefocus
go run myapp.go
```

I think this also addresses issue #16.

**Comment by R-Smith** [comment]
I tried the mousefocus branch and it seems to work well.  It fixes both issues I reported and so far I can't find any unwanted side effects.  I think it looks good.  Thanks for taking the time to look into this.

**Comment by gcla** [comment]
np, thanks for the bug report :) I'll close this now
