### ISSUE TITLE
When running hello world code: 30:22: undefined: text.TextContentSegment

### ISSUE THREAD

**Issue by richstokes** [gcla/gowid#18]

**Comment by gcla** [comment]
Hi @richstokes - I'll look into this. I should make a bug template of some sort, but would you mind sending me

- the value of `TERM` and the terminal emulator you're using
- if you have it, the full backtrace?

I pushed a couple of changes yesterday to gowid, so worth making sure you're up to date too.

**Comment by richstokes** [comment]
Thanks;

```
echo $TERM
xterm-256color
```

iTerm2 on MacOS. Not sure how to get the full trace - thats literally all thats printed:

```
go run hello.go
# command-line-arguments
./hello.go:30:22: undefined: text.TextContentSegment
```

On the latest

**Comment by gcla** [comment]
@richstokes - sorry to waste your time - the documentation has an error, I'll fix it now.

**Comment by gcla** [comment]
Hi - please could you try replacing "TextContentSegment" with "ContentSegment" in your example.

**Comment by richstokes** [comment]
That has fixed it :)

**Comment by gcla** [comment]
thanks, I'll close this out
