### ISSUE TITLE
gowid does not correctly handle text where runes are width >1

### ISSUE THREAD

**Issue by gcla** [gcla/gowid#2]
e.g. 你好，世界

**Comment by srlehn** [comment]
https://github.com/mattn/go-runewidth probably helps

**Comment by gcla** [comment]
Some fixes are now present in the widerunes branch. I'll merge these when I feel more confident in them.

**Comment by gcla** [comment]
If you want to try these changes, there are some simple instructions in this issue:

https://github.com/gcla/gowid/issues/1#issuecomment-488917734

**Comment by gcla** [comment]
Changed merged to master - closing this issue.
