### ISSUE TITLE
gowid.UrwidColor is invalid

### ISSUE THREAD

**Issue by deanchou** [gcla/gowid#21]
panic: Color UrwidColor(dark gray) of type *gowid.UrwidColor is invalid

goroutine 1 [running]:
github.com/gcla/gowid.(*UrwidColor).ToTCellColor(0xc0000aa880, 0x3, 0x639a40)
	/data/code/go/pkg/mod/github.com/gcla/gowid@v1.0.0/decoration.go:627 +0x4a6
github.com/gcla/gowid.IColorToTCell(0x6379e0, 0xc0000aa880, 0x1, 0x3, 0xc000018170)
	/data/code/go/pkg/mod/github.com/gcla/gowid@v1.0.0/decoration.go:1062 +0x3b

**Comment by gcla** [comment]
Hi - thanks for the report. I think this problem is fixed by the following commit:

https://github.com/gcla/gowid/commit/8202e3a669491853952ed674a5c81bf049f44dac

Would it be possible for you to update your project to use the latest? If you are using go modules, I think this command should work:

```bash
go get github.com/gcla/gowid@4855ffce5278a50a34e6b13b833b05e1667fd35c
```

**Comment by deanchou** [comment]
Updated and test passed
Thank you
