### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by dawidd6** [gcla/gowid#26]
Previously on Debian packaging of `termshark`... :laughing: 

We currently have 1.0.0 release of this library packaged in Debian. Could you create a new release, so we don't have to jump to different versioning (git)?

**Comment by gcla** [comment]
Hi! Yes, absolutely, I'll do it now :-)

**Comment by gcla** [comment]
Just pushed a tag - v1.1.0

**Comment by dawidd6** [comment]
Thanks for quick reaction!
