### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by ssgelm** [gcla/gowid#30]
Hi! I am working on the Debian packaging for termshark and I see that it requires functionality that is not yet in a tagged version of gowid. If necessary I can just package it based on the appropriate git sha but would you be willing to cut a new tagged release of gowid? If so it would make things easier for me!

**Comment by gcla** [comment]
Hi @ssgelm! Yes, would a tag < v1.0 work for your packaging requirements? Sorry for the delay in replying, and thank you for packaging termshark :-)

**Comment by ssgelm** [comment]
Yeah honestly any version (greater than the current release of course!) is totally fine, just a little cleaner to package actual releases than random git commits, though we realistically end up doing that a ton too... 😄

**Comment by gcla** [comment]
I just pushed v1.2.0 :-)
