### ISSUE TITLE
Tutorial 1 prints debug info on Windows

### ISSUE THREAD

**Issue by R-Smith** [gcla/gowid#5]
On Windows 10, the first application in the tutorial that is supposed to print 'hello world' on the screen is instead printing a line of debug info:

`time="2019-0518T22:37:17-07:00" level=info msg="Terminal was resized" event="&{{13776608856134938696 7999262101 0x69dee0} 148 30}"`

Go 1.12.  Windows 10.

**Comment by gcla** [comment]
Thanks, and Doh! I'll look into this.

**Comment by gcla** [comment]
Hi - I changed the app default to log to a file named after the running executable, rather than stdout.
